### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Axland233** [JHue58/ChatLearning#79]
windows sever 2022，使用的是exe包
报错如下
```json
 欢迎使用ChatLearning应用 版本号： 3.0.3
 输入help来查看指令列表吧！
 Traceback (most recent call last):
  File "Chatmain.py", line 2202, in <module>
  File "simuse.py", line 64, in Get_Session
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[6776] Failed to execute script 'Chatmain' due to unhandled exception!

```

**Comment by Axland233** [comment]
原谅我不太会写markdown，呜呜呜qwq

**Comment by MC57348** [comment]
+1

**Comment by YuWan886** [comment]
我也出现了这个问题

> windows sever 2022，使用的是exe包 报错如下
> 
> ```json
>  欢迎使用ChatLearning应用 版本号： 3.0.3
>  输入help来查看指令列表吧！
>  Traceback (most recent call last):
>   File "Chatmain.py", line 2202, in <module>
>   File "simuse.py", line 64, in Get_Session
>   File "json\__init__.py", line 346, in loads
>   File "json\decoder.py", line 337, in decode
>   File "json\decoder.py", line 355, in raw_decode
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> [6776] Failed to execute script 'Chatmain' due to unhandled exception!
> ```
最后发现是port填写错误了，改正后正常启动
