### ISSUE TITLE
启动时抛出异常

### ISSUE THREAD

**Issue by simontombu** [JHue58/ChatLearning#87]
启动时抛出异常

抛出异常，已记录到日志(log.log文件)
Traceback (most recent call last):
  File "ChatClass.py", line 407, in run
  File "ChatMerge.py", line 96, in main
  File "ChatMerge.py", line 78, in getfile
  File "ChatMerge.py", line 25, in Merge
  File "ChatClass.py", line 46, in pickle_load
EOFError: Ran out of input

后续可以正常运行，但是使用check命令导致无响应

**Comment by Nana-Miko** [comment]
删除wordstock里面0kb的文件
